Repository anarock/pebble, pull requests merged in 2023-03, with the labels that each got.

#433 fix icons file
  packages/pebble-shared/icons.json
Labels: bug

#434 add gap in OptionGroupCheckBox footer actions
  packages/pebble-web/src/components/styles/OptionGroupCheckBox.styles.ts
Labels: design

#429 generate Icon enum
  packages/pebble-shared/.gitignore
  packages/pebble-shared/package.json
  packages/pebble-shared/scripts/generateIconEnum.js
  packages/pebble-shared/src/index.ts
Labels: tech task

#439 add outline button
  packages/pebble-web/src/components/Button.tsx
  packages/pebble-web/stories/button.story.tsx
Labels: tech task

#438 Sidebar height
  packages/pebble-web/src/components/Sidebar.tsx
Labels: tech task

#436 Add grade line icon
  packages/pebble-shared/icons.json
  packages/pebble-shared/svgs/grade-line.svg
Labels: design

#441 Pdf Image Icons added
  packages/pebble-shared/icons.json
  packages/pebble-shared/svgs/image.svg
  packages/pebble-shared/svgs/pdf.svg
Labels: design

#437 Rental icons
  packages/pebble-shared/icons.json
  packages/pebble-shared/svgs/door-front.svg
  packages/pebble-shared/svgs/person-search.svg
Labels: design

#425 Post sales
  packages/pebble-web/src/components/Input.tsx
  packages/pebble-web/src/components/Select.tsx
  packages/pebble-web/src/components/Sidebar.tsx
  packages/pebble-web/src/components/styles/Modal.styles.ts
  packages/pebble-web/src/components/typings/Input.ts
  packages/pebble-web/src/components/typings/Select.ts
Labels: tech task

#445 fix tests
  packages/pebble-web/src/components/__tests__/__snapshots__/phonenumberinput.test.tsx.snap
Labels: tech task
